"""inicial

Revision ID: dacb87a30541
Revises: 
Create Date: 2022-10-31 21:03:39.271697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dacb87a30541'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Alumnos', sa.Column('Email', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Alumnos', 'Email')
    # ### end Alembic commands ###
